### PR TITLE
update pusher dependencies

### PR DESCRIPTION
**Pull request by billyroh**
(This was done by Connor and Neighman)

### CODE REVIEW

**Comment by billyroh** [comment]
The test says that `bin/ci/install` failed? @connorjacobsen

**Comment by connorjacobsen** [comment]
@billyroh Yeah that's what I expected it would be. Will take a look shortly.

**Comment by billyroh** [comment]
@connorjacobsen has identified the issue that's causing the test to fail. He said he'll push something up today.

**Comment by connorjacobsen** [comment]
Fixed the build and the tests pass 🎉

**Pull request merged**
